### ISSUE TITLE
Can't use book to enchant in survival

### ISSUE THREAD

**Issue by grandpaslab** [Geolykt/EnchantmentsPlus#24]
We've installed EnchantmentsPlus on our 1.16.1 server, and we've found that we can't use a book to enchant any item in survival mode. Works fine in creative. Are we doing something wrong, or is it broken?

**Comment by Geolykt** [comment]
Could be a permission issue, could be something else. I believe that it is likely something to do with incompatible tools.

**Comment by Geolykt** [comment]
Could you provide your configurations? It helps me to reproduce your issue. Additionally I would like to know if you are using CB (please don't), Spigot or Paper

**Comment by grandpaslab** [comment]
configs: https://drive.google.com/drive/folders/1Y2rkJrrPimmqexcCafLvjDJPNr9C1j9k?usp=sharing

We're using Spigot.

**Comment by Geolykt** [comment]
If I'm not fully wrong there's currently a bug with our code within spigot which is "fixed" under paper (or at least was a month ago).
 Fixing it would require some non-standard things, although isn't impossible

**Comment by Geolykt** [comment]
However your issue is based on the config and can be fixed by adding 
`    - "ENCHANTED_BOOK"`
to tools.axe, tools.pickaxe, etc. in the magicCompat.yml. It's an oversight from me that I did a few versions ago, which is why it's a bit borked.

So it would look something like
```yml

[...]
    - "DIAMOND_SWORD"
    - "NETHERITE_SWORD" # 1.16 and beyond
    - "FISHING_ROD"
    - "BOW"
    - "SHEARS"
    - "FLINT_AND_STEEL"
    - "ENCHANTED_BOOK"
  axe:
    - "WOODEN_AXE"
    - "STONE_AXE"
    - "IRON_AXE"
    - "GOLDEN_AXE"
    - "DIAMOND_AXE"
    - "NETHERITE_AXE" # 1.16 and beyond
    - "ENCHANTED_BOOK"
  pickaxe:
    - "WOODEN_PICKAXE"
    - "STONE_PICKAXE"
    - "IRON_PICKAXE"
    - "GOLDEN_PICKAXE"
    - "DIAMOND_PICKAXE"
    - "NETHERITE_PICKAXE" # 1.16 and beyond
    - "ENCHANTED_BOOK"
[...]
```
